name: Event Filter Practice

on:

  # 1. Push Event
  push:
    branches:
      - main

  # 2. Pull Request Event
  pull_request:
    types:
      - opened
      - closed

  # 3. Issue Event
  issues:
    types:
      - opened

jobs:

  demo-job:

    runs-on: ubuntu-latest

    steps:

     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Create Report File
       run: echo "GitHub Actions Artifact Practice" > report.txt

     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
          name: practice-report
          path: report.txt