name: Build, Test and Deploy

on:
  push:
    branches: [main]

jobs:
  # ── JOB 1: Build ──────────────────────────
  build:
    name: "🔨 Build Application"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ----------------------------------------
      # Step 2: Setup Python
      # ----------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ----------------------------------------
      # Step 3: Cache pip Dependencies
      # ----------------------------------------

      # ----------------------------------------
      # Step 4: Install Dependencies
      # ----------------------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ----------------------------------------
      # Step 5: Run Python Application
      # ----------------------------------------
      - name: Run Application
        run: python python-mod.py

      # ----------------------------------------
      # Step 6: Run Tests
      # ----------------------------------------
      # - name: Run Tests
      #   run: pytest

      # ----------------------------------------
      # Step 7: Generate Report File
      # ----------------------------------------
      - name: Create Build Report
        run: |
          mkdir reports
          echo "Python build completed successfully" > reports/build-report.txt

        

      # ----------------------------------------
      # Step 8: Upload Artifact
      # ----------------------------------------
      - name: Upload Build Report
        uses: actions/upload-artifact@v4
        with:
          name: python-build-report
          path: reports/

      - name : Deployment done
        run : |
          echo "All set to done"

  call-workflow:

    uses: ./.github/workflows/original_workflow.yml


  test:
    name: "⬇️ Download Artifact Job"

    runs-on: ubuntu-latest

    needs: build

    steps:

      # Download Artifact
      - name: Download Python Report
        uses: actions/download-artifact@v4
        with:
          name: python-build-report
          path: downloaded-report/

      # Show Downloaded Files
      - name: Verify Downloaded Files
        run: |
          echo "Downloaded Files:"
          ls -R downloaded-report/

      # Display File Content
      - name: Read Report File
        run: |
          cat downloaded-report/build-report.txt

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
        
     
  # # ── JOB 2: Test ───────────────────────────
  # test:
  #   name: "🧪 Run Tests"
  #   runs-on: ubuntu-latest
  #   needs: build                    # Run after build

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: ⬇️ Download Build
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: app-build           # Same name as upload
  #         path: ./dist/
  
  #     - name: Deploy App
  #       run: |
  #         echo "Files ready to deploy now:"
